name: Build and Test

on:
  push:
  pull_request:
    
permissions:
  packages: write
  contents: write
  
jobs:
  build-dotnet-library:
    uses: ktsu-dev/workflows/.github/workflows/build-dotnet-library.yml@main
    secrets: inherit
