name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    
permissions:
  packages: write
  contents: write
  
jobs:
  build-dotnet-library:
    uses: ktsu-dev/workflows/.github/workflows/build-dotnet-library.yml@main
    secrets: inherit
