name: .NET Library Pipeline

on:
  schedule:
    - cron: "* * * * *"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  packages: write
  contents: write
  
jobs:
  dotnet-library:
    uses: ktsu-dev/workflows/.github/workflows/dotnet-library.yml@main
    secrets: inherit
